### PR TITLE
All of my contributions to date

### PR DESCRIPTION
**Pull request by ChadAlanJackson**
I know you're working on getting a way to have a library of creation resources and patches.  But in the mean time, I thought I'd toss everything I've done to date your way.

### CODE REVIEW

**Comment by Jaeiya** [comment]
I'll have HanFox look at this as well.

We're still not sure what we're going to be doing.

**Comment by Jaeiya** [comment]
Ok I've had a chance to look at your contributions.

First of all HanFox and I agreed that some files don't need to be duplicated:
`bookshelf, ladder, apple, bowl, leather, paper, rod, softball, stick, and string`

Next is, I have no idea what you've actually committed haha. What are `.ace` and `.cs` files? What is the goal of your source and what program do I need to actually take a look at it?

**Comment by ChadAlanJackson** [comment]
The goal wasn't to duplicate, at the time of creation there were no source PSDs available for any of those. Since those seemed to be files that people were customizing on a fairly regular basis I thought having useful and usable PSDs would be handy. At the time I did those, everything was in un-layered PNG format. And not everything was in 512 x 512.
Some of those are Color studio source files that are the source files for creating those color palettes, those were from our discussion around encouraging people to adopt some level of material color standards. You may have decided against that by now, but the bones are there...
Does that help?
On Sun, Mar 29, 2015 at 3:56 PM, Aedaeum notifications@github.com wrote:Ok I've had a chance to look at your contributions.

First of all HanFox and I agreed that some files don't need to be duplicated:
bookshelf, ladder, apple, bowl, leather, paper, rod, softball, stick, and string

Next is, I have no idea what you've actually committed haha. What are .ace and .cs files? What is the goal of your source?

**Comment by Jaeiya** [comment]
I think this is going to have to stay in a pending state as both HanFox and I agree that this repo is not a standard and Sphax is very difficult to develop standards with, because he's so busy.

This is basically a "wishful thinking" repo at this point. Once we can actually get the patch site working (which HanFox and I are in the process of doing) then we can start working on a resource repository. Also due to the size of these textures, we may have to look for an alternate distribution mechanism.... Github only allows 1 gig. 100s of 512x images adds up, especially if we're going to host PSDs.

I don't want your work to goto waste so I ask that you hold off any more work until we can confirm that this is going to go somewhere.

**Comment by ChadAlanJackson** [comment]
That works for me.  Why not reject the pull request for now, and let me
know if you'd like to revisit.

**Comment by maxiride** [comment]
It happened to me to read the comments on this pull request. This website @Aedaeum mentioned has been made?

Regarding the file size limit that is related to each repo thus making a repo for each patch more practical.

**Pull request closed without merging**
